### ISSUE TITLE
Bitcoin Primitives

### ISSUE THREAD

**Issue by roshii** [gdkrmr/BTCParser.jl#2]
Hi,

As said a couple of month ago on [Discourse](https://discourse.julialang.org/t/in-development-bitcoin-jl-a-julia-bitcoin-library/17944/49?u=roshii) my implementation of Bitcoin.jl needs to be restructured and considering the great job you did with your implementation, I'd rather use your code directly especially with regards to your primitives implementation.

I was thinking of stripping your code down to UInt256, Block, and Transaction types only and make it a BitcoinPrimitives.jl package that I could use for my project (similar to bitcoin-core [implementation](https://github.com/bitcoin/bitcoin/tree/master/src/primitives) in a way) 

Can you let me know if you wish to create that package yourself or if I may just fork and package directly?

Thanks

**Comment by gdkrmr** [comment]
Go ahead and just fork it, I think it is a good idea to have some standardized data types to have better interoperability, I am currently busy with other projects but may contribute at some point. Please don't forget to mention me as the original creator. Here are some thoughts on what I did:

- I store some length fields, (e.g. `Block.transaction_counter`, etc.) which are not really necessary in a language like Julia (they can be accessed by something like (`length(block.transaction_counter)`), I wanted to remove them at some point and replace them by properties, so this would be non-breaking.

- I am not sure if defining `UInt256` as a `primitive type` was the best decision, an `NTuple{32, UInt8}` would make manipulation easier and (probably) more performant. You currently have to allocate arrays for some transformation operations and I think there is no way around this in Julia.

- There may also be a naming clash with future versions of Julia that will probably have a native `UInt256` type at some point.

- And there is https://github.com/rfourquet/BitIntegers.jl which could be considered as a replacement for `UInt256`.

- I am saving `Header` as a `NTuple{80, UInt8}`, this has the same memory layout as the blocks on disk but a different memory layout as a `struct` of the corresponding fields but I think it is faster for reading from disk but reading the fields may be slower on older processors due to alignment issues---I think I made the right call here.

- You are probably more interested in the serializations bitcoin uses for network communication, I think they are different from the serializations used for disk storage, I am not sure I this has to be considered for `BitcoinPrimitives.jl`.

**Comment by roshii** [comment]
> Go ahead and just fork it, I think it is a good idea to have some standardized data types to have better interoperability, I am currently busy with other projects but may contribute at some point. Please don't forget to mention me as the original creator.

Let's fork then :) I won't forget to mention you off course.

>     * I store some length fields, (e.g. `Block.transaction_counter`, etc.) which are not really necessary in a language like Julia (they can be accessed by something like (`length(block.transaction_counter)`), I wanted to remove them at some point and replace them by properties, so this would be non-breaking.

I was indeed planning at stripping it down to its bare minimum



>     * I am not sure if defining `UInt256` as a `primitive type` was the best decision

As a matter of facts I have tried to replace my implementation which uses `Vector{UInt8}` with `BitIntegers.jl` but that brought more problems than it did solve... Reading your comment I may switch to `NTuple{32, UInt8}` which definitely makes sense.

>     * I am saving `Header` as a `NTuple{80, UInt8}`

That is an interesting approach, I will keep it as is and investigate performance implication versus a `struct` layout as I did. 

>     * You are probably more interested in the serializations bitcoin uses for network communication

So far yes and I did not even think serialization could be different. I'll take a closer look and adapt accordingly. As I see it, `BitcoinPrimitives.jl` should cover all use case

**Comment by roshii** [comment]
Just for reference, `BitcoinPrimitives.jl` is hosted at https://gitlab.com/braneproject/BitcoinPrimitives.jl and mirrored at https://github.com/roshii/BitcoinPrimitives.jl

**Comment by gdkrmr** [comment]
Great, I think it is great to have this in a separate package as a basis for a Bitcoin ecosystem in Julia!
